---
- name: Create hive_tar directory
  hosts: servers
  become: yes
  vars_files:
    - /data/work/hive_3.1.3_ansible/main.yml
  tasks:
    - name: Create hive_tar directory
      file:
        path: "{{ hive_tar_path }}"
        state: directory

    - name: Create work directory
      file:
        path: "{{ work_dir }}"
        state: directory


- name: Copy hive_tar to servers
  hosts: localhost
  become: yes
  vars_files:
    - /data/work/hive_3.1.3_ansible/main.yml
  tasks:
    - name: tar_scp.sh Start
      shell: "{{ play_book_dir }}/tar_scp.sh {{ play_book_dir }} {{ hive_tar_path }}"


- name: Extract hive_tar
  hosts: servers
  become: yes
  vars_files:
    - /data/work/hive_3.1.3_ansible/main.yml
  tasks:
    - name: Extract the hive tarball
      unarchive:
        src: "{{ hive_tar_path }}/{{ hive_tar_filename }}"
        dest: "{{ work_dir }}"
        remote_src: yes


- name: entrypoint_sh start
  hosts: localhost
  become: yes
  vars_files:
    - /data/work/hive_3.1.3_ansible/main.yml
  tasks:
    - name: entry_point_sh start
      shell: "{{ play_book_dir }}/entrypoint.sh {{ play_book_dir }} {{ work_dir }} {{ postgresql_jar_filename }}"
